[tools]
# cli
"1password-cli" = "latest"
"bat" = "latest"
"delta" = "latest"
"eza" = "latest"
"fd" = "latest"
"fzf" = "latest"
"kubectl" = "latest"
"lazydocker" = "latest"
"lazygit" = "latest"
"neovim" = "latest"
"rclone" = "latest"
"ripgrep" = "latest"

# java
"java" = "corretto-21"

[env]
EDITOR = "nvim"
VISUAL = "nvim"
